---
abstract: 'Store virtual columns inside another column.'
author:
  - 'Pronin Oleg <syber@cpan.org>'
build_requires:
  DBD::SQLite: 1.13
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-FrozenColumns
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.07003
  JSON::XS: 0
  Storable: 2.15
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
